### ISSUE TITLE
Reconcile missing historic bounties

### ISSUE THREAD

**Issue by JamieSlome** [418sec/huntr#1327]
It was raised that pre-GitHub database vulnerabilities/bounties are missing, meaning that Timeline activities are not being tracked on some profiles.

Thanks to @ferretwithaberet for raising this issue!

e.g. 039-js-valib and 053-js-vizion are old IDs that were not translated over to the new DB.

We need to:

1. Reconcile all previous vulnerabilities from the old database that are missing
2. Create vulnerability.json and README.md files for each
3. Associate the correct Discloser and Fixer IDs
4. Add these events to the Timeline database

We should look to have this done by the end of the week - cheers!

**Comment by benharvie** [comment]
I believe this was the job of the `importer`, which has since been deprecated but here is the historic code for reference: https://github.com/418sec/huntr/blob/c42bfd30e39cb9b4333cebc39f2a5556f423916e/tools/importer/index.js

I will have a look into why these ID's were skipped in the process and populate as needed.

Cheers 👻

**Comment by JamieSlome** [comment]
@benharvie - great!

I have sorted out those two missing bounties for now, but let's see if we can fill in the rest too.

Cheers! 🍰

**Comment by ferretwithaberet** [comment]
Thank you!
