### ISSUE TITLE
Allow a reporter to decide whether a report is private or public.

### ISSUE THREAD

**Issue by JamieSlome** [418sec/huntr#2000]
- [ ] Discloser can select opt-in for private disclosure

**Comment by wow64bb** [comment]
If a report is private, I believe that the report should satisfy the following requirements: (using https://huntr.dev/bounties/1-other-TryGhost/Ghost/ as example)

- [x]  The affected repo should not be disclosed
- [x] The vulnerability category should not be disclosed
- [x] The URL of the private report should just return 403 for users other than the maintainer, reporter, staff

As for now, the only way for Huntr.dev to contact maintainers about a security vulnerability is via opening an issue directly using @huntr-helper. Since issues can be viewed by anyone, this could upset some security folks because most wanna stay private about security stuffs.

Hence, I believe that when the reporter wants to make a report private, he/she can optionally provide the security contact email/security web page/responsible disclosure page for the specific repository.

Using TryGhost as an example again, they have their own email specifically to handle security issues which is ```security@ghost.org``` as documented in https://ghost.org/docs/security/#reporting-vulnerabilities. Other than that, the team will actively work on a patch for the fix and most importantly publicly disclose it in next release. Lastly, depending on the maintainer whether they are CVE CNA themselves or not, huntr.dev will request CVE for vulnerability (or the [maintainer request it via the Security tab](https://docs.github.com/en/code-security/security-advisories/about-github-security-advisories)).

In my humble opinion, I propose the following process to disclose private vulnerabilites.

1. The reporter decided to disclose a vulnerability privately.
2. The reporter fill in vulnerability details including links or email to the security team contact. If this is not filled in, huntr.dev should find a way to contact the maintainer via email. The chance of this should be low since there is a high possibility that the reporter needs to follow the responsible disclosure guidelines and rules to report the vulnerability to the maintainer.
3. After finishing submitting the vulnerability details, the reporter sends an email to the security contact email and tell them to visit the disclosure page in huntr.dev 
4. The maintainer verifies the vulnerability is valid
5. The maintainer chooses to patch the vulnerability themselves or ask help from the community (likely the first option)
6. The reporter is paid so he/she gets to survive to the next month
7. The maintainer should provide estimated date to allow public disclosure of the vulnerability
8. The vulnerability goes full public disclosure, depending on the reporter and maintainer they should choose to redact the conversation between them (or not)

Obviously there are some flaws in the process such as some maintainers [prefer to not give permissions](https://github.com/szTheory/exifcleaner/issues/146#issuecomment-831217641) to Huntr.dev website over Github account. In this case Huntr.dev would need to contact the security team to verify the vulnerability and link the disclosure page with the vulnerability page together.

Anyway, this is just my humble idea, please let me know if there is any suggestions/objections about this. Thanks.

**Comment by adam-nygate** [comment]
@wow64bb Thanks for the comment!

Do you think #1982 could solve this?

It would default reports to private if we detect a SECURITY.md (presuming this is the way maintainers state they want coordinated disclosure). We would then scan the file for an email, and email that a magic link so that they could auth to review the report (that way they don't have to sign-in with GitHub).

**Comment by wow64bb** [comment]
That would work too, also check for https://github.com/418sec/huntr/security/policy which is the Security tab.

Although there are some organizations that does not include their security contact in their Github repository (requires some Googling), it should be enough for normal repository contacts.

**Comment by psmoros** [comment]
@JamieSlome this doesn't apply anymore right?

**Comment by JamieSlome** [comment]
@psmoros - I think the reason that this was opened was to address information being responsibly disclosed, and so I do not believe this applies anymore.

**Comment by psmoros** [comment]
noice <3
