### ISSUE TITLE
Stop automatic opening of issues on repos unsolicited

### ISSUE THREAD

**Issue by mcollina** [418sec/huntr#2011]
I think OSS maintainers should opt-in to your platform and you should not be opening issues on repositories and consider it as the last measure after:

1. you have followed the security policy of a project and received no answer
1. you have tried to contact the owner of the module/package on the official email of the project

After _at least a month_, you might consider the package unmaintained and open a public issue.

Your current behavior __damages__ Open Source projects health and sustainability. Consider reversing this extremely bad pattern.

My understanding is that this mass promotion of your service is against https://docs.github.com/en/github/site-policy/github-acceptable-use-policies. I have already pinged folks at Github to check.

**Comment by JamieSlome** [comment]
Hello @mcollina - we are currently in the process of implementing this new process, right now.

Apologies for the inconvenience! 🍰

**Comment by mcollina** [comment]
Thanks

**Comment by MylesBorins** [comment]
You had communicated that you were launching a change today to ensure that the new process would respect a `SECURITY.md` file but I think that in retrospect that really isn't sufficient. Even with that change in place the bot has opened 14 issues in the last 3 hours since you "rolled out the change", 4 of these issues explicitly state that there might be ["hard coded credentials in the repo"](https://github.com/issues?q=is%3Aissue+is%3Aopen+author%3Ahuntr-helper+Potential+Use+of+Hard-coded).

A bad actor could literally use the search query I just linked to to find repos where they might be able to exfiltrate credentials. This is exactly why your current process of opening issues with the title of the vulnerability is not only a bad practice but is legitimately dangerous and making OSS security worse.

Please stop opening public issues with the title of the vulnerability!

**Comment by adam-nygate** [comment]
Hey @MylesBorins, thanks for the additional feedback. I've just deployed a change to remove the summary from the issue title/description.

Whilst I agree with your point, any bad actor could use a variety of simpler means to exfiltrate credentials (en masse) if they were interested (e.g. GitHub search dorks, codeql, grep.app - I only know this because a lot of the researchers in our community have explained to us how they go about hunting, and so it seems like these tools are used pretty commonly). I think that hopefully by making the maintainers aware of the issue, its impact, and encouraging both discovery and remediation, that ultimately it can lead to a safer environment for everyone.

Not saying that our process is perfect though, quite the opposite! We're just trying to iterate fast to find something that works for everyone 😊
