### ISSUE TITLE
As a user, I would like to edit the entire report.

### ISSUE THREAD

**Issue by JamieSlome** [418sec/huntr#2018]
Users have requested multiple times to update their CVSS score.

- [x] Allow the editing of a vulnerability by the discloser

**Comment by Saphall** [comment]
Hello @JamieSlome , what if Disclosers change their CVSS score after it has been validated and increase it? They may actually climb up the leaderboard easily. What about giving Maintainers option to decide the severity themselves after submission and decrease or increase it according only if needed, and not  the Discloser?

**Comment by JamieSlome** [comment]
@Saphall - nice idea, we can certainly lockdown this functionality to the maintainer. Perhaps the discloser has a way of suggesting new CVSS scores, and the maintainer can confirm or deny?

**Comment by Saphall** [comment]
Yeah that seems fine in-case the CVSS score has to be updated later by any case. Thanks.

**Comment by JamieSlome** [comment]
Awesome, will make sure to keep this ticket updated when we start working on it, to keep everyone aware of progress.

Thanks! 🍰

**Comment by adam-nygate** [comment]
I think it makes sense that only the discloser should be able to edit their report (including CVSS) and then the maintainer can only comment and confirm its validity. After validation, the report should be locked so that it can no longer be edited.

So in this scenario, the discloser should update the report (proposing the CVSS) and the maintainer can confirm its validity once they're happy. How does this sound?

**Comment by JamieSlome** [comment]
Addressing this with our internal ticket: https://github.com/418sec/huntr-platform/pull/1391

**Comment by JamieSlome** [comment]
@adam-nygate - stabilised 👍

**Comment by Saphall** [comment]
**_**Good to hear !**_** 😁
