### ISSUE TITLE
Allow discloser to submit a report with a contact e-mail for outreach.

### ISSUE THREAD

**Issue by JamieSlome** [418sec/huntr#2026]
Suggested by @ranjit-git.

**Comment by adam-nygate** [comment]
We won't be able to automatically verify if the contact is legitimate, and so won't know if we can disclose, and whether we can trust their judgement on the validity of the report.

Any ideas on how we can implement this without these issues?

**Comment by 0xcrypto** [comment]
One way to confirm the verify the legitimacy of an email is to look at the Website field of a repository, if not present, look at owner's website field and then check the email against the host of that website. 

Another way can be just ignore the legitimacy check and send a link of report to the email. Since only maintainer can see it, legitimacy shouldn't be a problem.

**Comment by psmoros** [comment]
@adam-nygate do you agree with the reasoning or is it infeasible?

**Comment by adam-nygate** [comment]
I don't think the above logic is sound enough, but, we should be able to better enable non-magic link interactions via the recently implemented tryClaimOwnership functionality (allowing any maintainer with push access to the repo to login and see the report)

**Comment by psmoros** [comment]
makes sense! closing then :)
