### ISSUE TITLE
As a user, I want to understand how/when a prize pot will be topped up.

### ISSUE THREAD

**Issue by B3EF** [418sec/huntr#2125]
It would be nice if there is a widget for corresponding repos at the bounties checking page that shows the time which the bounty pot gets refueled.

**Comment by adam-nygate** [comment]
Nice to see you again @B3EF!

The prize pots re-fill in a moving window, meaning that the prize pot will only re-fill after 30 days from paying out the existing bounties.

I.e:
- Prize pot contains $100
- Disclosure submitted valued at $50 on 1st June (remaining pot = $50)
- Disclosure submitted valued at $50 on 10th June (remaining pot = $0)
- Prize pot contains $0 on 30th June
- Prize pot contains $50 on 1st July
- Prize pot contains $100 on 10th July (if no other bounties have been claimed since 10th June)

**Comment by B3EF** [comment]
oh ok, but a widget or some kind of frame showing this info in a graphical manner will be nice to figure things out, and it would be greatly understandable for a noobie exploring huntr.
also, the bounties eaten by invalid reports don't seem to be adding up with the bounty pot.

**Comment by adam-nygate** [comment]
> oh ok, but a widget or some kind of frame showing this info in a graphical manner will be nice to figure things out, and it would be greatly understandable for a noobie exploring huntr.

Will rename this ticket to better focus on this.

> also, the bounties eaten by invalid reports don't seem to be adding up with the bounty pot.

Once a bounty has been invalidated, the money reserved for it is returned to the prize pot.

**Comment by JamieSlome** [comment]
@B3EF - this has now been deployed ❤️ 

You can try it out by sticking a repository URL in the target finder against a repository with reports. If the pot has been consumed, you will see a countdown timer on the displayed repository.

Would be great to get your feedback here!
