### ISSUE TITLE
need a search + sort option in reports page 

### ISSUE THREAD

**Issue by b1nslashsh** [418sec/huntr#2127]
Need a search and sort option on the reports page
https://www.huntr.dev/users/b1nslashsh/reports

**Comment by adam-nygate** [comment]
Hey @b1nslashsh, I'm just wanting to convert this into a user story, so can you help me understand how you would use searching/sorting on the reports page to achieve something you want/need?

**Comment by b1nslashsh** [comment]
Hey @adam-nygate 

As a user in my case pre-sorting it by date will be helpful

**Comment by adam-nygate** [comment]
> As a user in my case pre-sorting it by date will be helpful

Why will sorting by date help you?

**Comment by b1nslashsh** [comment]
@adam-nygate To save time , yesterday a maintainer asked  a file for a pending report, I took some time to catch it, I do not know why it is arranged this way and how

**Comment by adam-nygate** [comment]
If I can understand how/why you need something, it helps us make sure that we're building something that will solve the underlying problem.

In this case, it sounds like you need to sort by pending, so that you can quickly pass maintainers the URL for pending reports, if asked - is this the case? If so, could you let me know how you pass the URL to the maintainer?

**Comment by JamieSlome** [comment]
@psmoros - do you think we will include this in the scope of maintainer delight improvements?

**Comment by psmoros** [comment]
tracked in #2163 :)
