### ISSUE TITLE
Researchers can customise report titles

### ISSUE THREAD

**Issue by TheCrott** [418sec/huntr#2170]
Currently researchers cannot create new report title and it make a title from template. As a researcher, I want to able to create report title when creating a new report.

BAD: `XSS (Stored) in repo/repo`
GOOD: `Stored XSS in /admin/stats.php`

@JamieSlome @psmoros

**Comment by psmoros** [comment]
Nice one @TheCrott ! If others +1 it we'll put it on the roadmap :)

**Comment by jaapmarcus** [comment]
I would be smart for SEO purpose to adjust it to Stored XSS in  /admin/stats.php  (repo/repo) or the other way around. As if the "Meta" card is shared it would be useful to include things as repo it self to be shared

How ever it would be nice instead of the "default" title to modify the title to:

Cross-Site Request Forgery token missing in /logout  (repo/repo) 

Sounds better then:

Cross-Site Request Forgery (CSRF) in repo/repo

**Comment by TheCrott** [comment]
@psmoros other researcher give +3 on @jaapmarcus reply, so I think this should be put in the roadmap

**Comment by psmoros** [comment]
Will do @TheCrott :)

**Comment by JamieSlome** [comment]
<img width="781" alt="Screenshot 2021-12-14 at 15 46 54" src="https://user-images.githubusercontent.com/55323451/146031420-ed4864ef-af2c-45f1-b63a-3d9fe2f0fbc5.png">

From @samus-aran with regards to reporting titles...

**Comment by JamieSlome** [comment]
@TheCrott @samus-aran @jaapmarcus

This has now been deployed and is now live 🎉 🚀 

Researchers can customize report titles when creating new reports and editing previous reports.
