### ISSUE TITLE
credit should be assigned for CVE-assigned tickets in Github 

### ISSUE THREAD

**Issue by bugruto** [418sec/huntr#2191]
## the idea is to implement credits to the reporter on the github advisories also for valid vulnerabilities .
![image](https://user-images.githubusercontent.com/98601906/152211462-77a5ee90-6299-477f-9570-6035c70cb72a.png) 

##  so that the reporter can have credits to it also on github 
![image](https://user-images.githubusercontent.com/98601906/152212117-096eb2ec-0fc6-440f-adf1-5af5da4ab012.png)

**Comment by Haxatron** [comment]
3rd party GH advisories do not get GHSA credits

**Comment by JamieSlome** [comment]
@bugruto - I do not believe that we can get the GHSA to show the researcher on our platform that reported the vulnerability, as I think this can only be done via the GHSA itself, rather than through the data received from the CVE database.

Let me know if you believe otherwise, and would be happy to re-address this.

Closing for now, but feel free to re-open if have any information to show otherwise on the above ❤️
